POST http://localhost:8080/create-rooms HTTP/1.1
Content-Type: application/json

{
    "roomCount": "9"
}

###

POST http://localhost:8080/create-participant HTTP/1.1
Content-Type: application/json

{
    "name": "Test"
}

###

GET http://localhost:8080/rooms HTTP/1.1

###

GET http://localhost:8080/waitingroom HTTP/1.1

###

POST http://localhost:8080/join HTTP/1.1
Content-Type: application/json

{
    "id": "67fc4b7fbe4ceb3e1d072da6",
    "roomNumber": "9"
}