# URL Variable
@url = http://localhost:8080

###

GET {{url}}/ HTTP/1.1

###
GET {{url}}/image HTTP/1.1

###
POST {{url}}/signup HTTP/1.1
Content-Type: application/json

{
    "username": "Tommy",
    "password": "UnsafePlaintext"
}

###
DELETE {{url}}/cookies HTTP/1.1

###
GET {{url}}/0.gif HTTP/1.1