GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tbXkiLCJpYXQiOjE3MzAzMTMzMTIsImV4cCI6MTczMDMxMzM3Mn0.UyeYKiisUd1fbe4C83LBiwi-U-V2hJXHx-1HJD2EoYs

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tbXkiLCJpYXQiOjE3MzAzMTMzMTIsImV4cCI6MTczMDMxMzM3Mn0.UyeYKiisUd1fbe4C83LBiwi-U-V2hJXHx-1HJD2EoYs"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9tbXkiLCJpYXQiOjE3MzAzMTMyMzF9.IB8RUYiBcsTYWvF-1__IgSKhcjtNJQXvScuoLDhHDoQ"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Tommy"
}