@HOST=http://localhost:8080
@USERNAME=tommy

### Get user by username
GET {{HOST}}/users/{{USERNAME}}

### Create user

POST {{HOST}}/users/create
Content-Type: application/json

{
  "username": "tommy"
}

### Successful login

POST {{HOST}}/users/login
Content-Type: application/json

{
  "username": "tommy"
}

### Failed login

POST {{HOST}}/users/login
Content-Type: application/json

{
  "username": "Kevin"
}

### Delete user

DELETE {{HOST}}/users/{{USERNAME}}