@HOST=http://localhost:8080
@USERNAME=Tommy

### Get user list
GET {{HOST}}/users/{{USERNAME}}

### Create user

POST {{HOST}}/users/create
Content-Type: application/json

{
  "username": "Tommy"
}

### Successful login

POST {{HOST}}/users/login
Content-Type: application/json

{
  "username": "Tommy"
}

### Failed login

POST {{HOST}}/users/login
Content-Type: application/json

{
  "username": "Kevin"
}

### Delete user

DELETE {{HOST}}/users/{{USERNAME}}